version: "3.8"
services:
  app:
    build: .
    ports:
      - "2704:2704"
    environment:
      - MONGO=mongodb://mongo:27017/hotelbooking
    depends_on:
      - mongo
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5